### ISSUE TITLE
Incompatible with ueberauth_github

### ISSUE THREAD

**Issue by arnaudlimbourg** [ueberauth/ueberauth_slack#13]
Hello,

It seems the current version is not compatible with oauth2 0.8.

I tried to update the calls but have had no success, I don't quite understand everything the code does (I have just started learning elixir).

After seeing the github strategy was updated I tried to follow the way it is donewith no success.

Any plans to update this strategy?

Thanks!

**Comment by zkwentz** [comment]
#16 was merged, this should be compatible with ueberauth_github now.

**Comment by doomspork** [comment]
@arnaudlimbourg I'm closing this for now as it should be resolved, please let me know if that is no longer the case 👍
