### ISSUE TITLE
Update oauth2 to > 0.8

### ISSUE THREAD

**Issue by zkwentz** [ueberauth/ueberauth_slack#15]

**Comment by jakewilkins** [comment]
Is this going to be merged?

I'd like to use both `ueberauth_slack` and `ueberauth_github` and I'm hitting a version mismatch error.

Thanks for the contribution btw!

**Comment by abadongutierrez** [comment]
I tried to use it with Phoenix 1.3 and I got this error:

```
Resolving Hex dependencies...

Failed to use "poison" (version 3.1.0) because
  ecto (version 2.2.4) requires ~> 2.2 or ~> 3.0
  oauth2 (version 0.6.0) requires ~> 1.3 or ~> 2.0
  phoenix (version 1.3.0) requires ~> 2.2 or ~> 3.0
  mix.lock specifies 3.1.0
```

Using the oauth v0.9 is needed

**Comment by zkwentz** [comment]
Resolved.
