### ISSUE TITLE
Publishing 0.5 to Hex

### ISSUE THREAD

**Issue by beedub** [ueberauth/ueberauth_slack#30]
Hey there,

I don't see 0.5 on https://hex.pm/packages/ueberauth_slack. Any chance 0.5 can be published there?

Thanks

**Comment by stoft** [comment]
Any news on this? After the lastest PR it's now at 0.6 in master but hex is on 0.4.1

**Comment by yordis** [comment]
@doomspork can you help us with this? I am having issues with Hex ...

**Comment by doomspork** [comment]
@yordis that has been on going for some time, could you please escalate that and get it fixed? We're back down to me be the only person maintaining and releasing 👎

**Comment by doomspork** [comment]
@stoft / @beedub `0.6.0` is released.

Apologizes for the delays, I'm dealing with some personal things and I'm not around much these days and it seems the other maintainers aren't either.  If either of you are interested, I'm always looking for others to join the team
