### ISSUE TITLE
Doesn't work with ueberauth 0.7.0

### ISSUE THREAD

**Issue by tomsharratt** [ueberauth/ueberauth_slack#38]
Authentication callback fails with CSFR error.
```
%Ueberauth.Failure.Error{message: "Cross-Site Request Forgery attack", message_key: :csrf_attack}
```

**Comment by Hanspagh** [comment]
Hi @tomsharratt.

This is linked to change made here https://github.com/ueberauth/ueberauth/pull/136
Something like this needs https://github.com/ueberauth/ueberauth_facebook/pull/65 needs to happen for the slack client aswell.

More docs can be found here https://github.com/ueberauth/ueberauth/blob/7ebc0aeeb17d0953bdc53a01018307fb03e0b189/lib/ueberauth/strategy.ex#L265

**Comment by stwf** [comment]
Great work on this! Works like a charm. Any chance you could push this new version to hex? TIA
