### ISSUE TITLE
Access raw data returned from Slack 

### ISSUE THREAD

**Issue by panayi** [ueberauth/ueberauth_slack#7]
Is there any way to access raw data within the callback method? Certain properties are missing, like the [team icon](https://api.slack.com/methods/team.info).

**Comment by hassox** [comment]
Currently I haven't put much raw info in it but it would go here: https://github.com/ueberauth/ueberauth_slack/blob/master/lib/ueberauth/strategy/slack.ex#L157

Would you be up for a PR?

**Comment by panayi** [comment]
Yes, will do. Thanks
